---
- hosts: local
  become_user: root
  become: yes
  gather_facts: no
  roles:
    - common
    - python3
    - system-config
    - synaptics # Settings for touchpad
    - vim       # Configuration for vim
    - spotify
    - google-chrome
    # - java
