---
- name: Update the repository cache "apt-get update"
  apt:
    update_cache: yes
    cache_valid_time: 84600
- name: Safe upgrade "apt-get upgrade"
  apt:
    upgrade: yes
- name: Ensure basic packages are installed
  apt: name={{ item }} state=present
  with_items:
    - aptitude
    - bash-completion
    - zsh
    - git
    - gcc
    - g++
    - valgrind
    - gdb
    - curl
    - wget
    - nmap
    - tree
    - vlc
    - htop
    - unzip
    - tar
    - gzip
    - bzip2
    - qpdfview
    - konsole
- name: Config konsole
  copy:
    src: konsole/
    dest: "{{ local_home }}/.local/share/konsole"
    owner: "{{ user }}"
    group: "{{ user }}"
  when: user != "root"
- name: Clone prezto (zsh config)
  git:
    repo: https://github.com/sorin-ionescu/prezto.git
    recursive: yes
    dest: "{{ local_home }}/.zprezto"
  ignore_errors: True
- name: Config zsh
  block:
    - copy:
        src: "{{ item }}"
        dest: "{{ local_home }}"
        owner: "{{ user }}"
        group: "{{ user }}"
        mode: 0644
      with_items:
        - .zlogin
        - .zlogout
        - .zpreztorc
        - .zprofile
        - .zshenv
        - .zshrc
    - copy:
        src: prompt_skwp_setup
        dest: "{{ local_home }}/.zprezto/modules/prompt/functions/"
        owner: "{{ user }}"
        group: "{{ user }}"
        mode: 0644
      
- name: Change default shell on zsh
  user:
    name: "{{ user }}"
    shell: /bin/zsh
